server:
  port: 8080

spring:
  application:
    name: projector
  jooq:
    sql-dialect: postgres
  mvc:
    static-path-pattern: /**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    io.github.pgatzka.projector: DEBUG
